---
title: "Data Wrangling"
output: github_document
---

# Section 1

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
#make sure you make a folder in your directory with all of the data
litters_df = janitor::clean_names(litters_df)
```

## Take a look at the data

Printing in the console

```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```


##Options to read CSV

```{r}
litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = F, na = c("", "NA", ".", 999))
#Helps you say ignore the missing data using the "" na funct.
#?readcsv() has more info
```

## Other file formats

Read in Excel File

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
## write these directly in the console to open dataset in new tab and to have more info for your excel datasheet
##View(mlb_df)        
##?read_excel        give you options for how you want to read in information
```

Read in SAS file

```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df
```

## Comparison w base r

what about? read.csv --> NO!!
  --> thats directly from r and weird
  
```{r}
litters_base = read.csv("data/FAS_litters.csv")
litters_readr = read_csv("data/FAS_litters.csv")

litters_base
##this one kinda sucks

litters_readr 
##this one is better/easier to look at
##DONT USE THE DOT CSV ONLY USE UNDERSCORE CSV!!!!
```


