---
title: "Tidy Data"
output: github_document
---


```{r setup}
library(tidyverse)
```

## pivot_longer

Load the PULSE data

```{r}
#doing sas load so you use haven but only need it once so do the :: not the library
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

WIDE format to LONG format

```{r}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  )

#pivot longer makes columns that are too wide longer
# this one specifies which rows you want bdi_score_bl:bdi_score_12m
#this part says heres the new name for the new thing  names_to = 
#this part deletes the unnecessary info bdi_score_ names_prefix = "bdi_score_",
```

```{r}
#rewrite combine and extend to add mutate step
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
 pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))

```

## 'pivot_wider'

Make up some data

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```

## Binding rows

Using LOTRRR data

now switch gears to new dataset. What happens when I have data in mulitple tables and I want to stack those rows up.

Step 1: import data
```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range ="B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range ="F3:H6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range ="J3:L6") %>% 
  mutate(movie = "return_king")
```

Bind all rows together

```{r}
lotr_tidy =
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
#this above moves movie to the first column
  pivot_longer(
    female:male,
    #shifting from female to male
    names_to = "gender",
    values_to = "words"
  )
```

